// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbm_mbjiZq406zGlVjeiiI-oak-NkHX9w',
    appId: '1:1075993512688:web:fbaf32d012616566b91035',
    messagingSenderId: '1075993512688',
    projectId: 'restaurant-app-970a8',
    authDomain: 'restaurant-app-970a8.firebaseapp.com',
    storageBucket: 'restaurant-app-970a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaqAOicYxkAzAFtOSnFGEyuH9MNZswcYI',
    appId: '1:1075993512688:android:cea7429191405db8b91035',
    messagingSenderId: '1075993512688',
    projectId: 'restaurant-app-970a8',
    storageBucket: 'restaurant-app-970a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtvrKEpRHlinGS2qGwf-5bQmq3-WjuDsM',
    appId: '1:1075993512688:ios:13ab2cc32afe2af3b91035',
    messagingSenderId: '1075993512688',
    projectId: 'restaurant-app-970a8',
    storageBucket: 'restaurant-app-970a8.appspot.com',
    iosBundleId: 'com.example.restaurantAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtvrKEpRHlinGS2qGwf-5bQmq3-WjuDsM',
    appId: '1:1075993512688:ios:0d2179d2486e0602b91035',
    messagingSenderId: '1075993512688',
    projectId: 'restaurant-app-970a8',
    storageBucket: 'restaurant-app-970a8.appspot.com',
    iosBundleId: 'com.example.restaurantAppFlutter.RunnerTests',
  );
}
